version: '3.9'

services:
  app:
    container_name: app
    build: .
    depends_on:
      - postgres
      - mongo
    env_file: '.env'
    ports:
      - '3000:3000'
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SMTP_HOST_MAILER=${SMTP_HOST_MAILER}
      - MAILER_USER=${MAILER_USER}
      - MAILER_USER_PASSWORD=${MAILER_USER_PASSWORD}
      - DB_HOST=postgres
      - DB_TYPE=${DB_TYPE}
      - DB_NAME=strikeball
    command: npm run start:dev
    restart: always
    networks: 
      - node-app

  mongo:
    container_name: mongo
    image: mongo:4.4.7-focal
    restart: always
    ports:
      - '27017:27017'
    networks: 
      - node-app

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - PG_DATA=/var/lib/postgresql/data
      - POSTGRES_DB=strikeball
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
    restart: always
    networks: 
      - node-app

networks:
  node-app:
    driver: bridge
